# Generated by Django 3.1.7 on 2021-02-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('region', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=75)),
                ('type', models.CharField(max_length=14)),
                ('status', models.CharField(max_length=14)),
                ('price', models.FloatField()),
                ('features', models.TextField()),
                ('image', models.ImageField(upload_to='pictures')),
            ],
        ),
    ]
