# Generated by Django 3.1.7 on 2021-03-03 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('region_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoverdeapp.region')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('content', models.TextField()),
                ('address', models.CharField(max_length=60)),
                ('price', models.FloatField()),
                ('features', models.TextField()),
                ('image', models.ImageField(upload_to='pictures')),
                ('phone', models.CharField(max_length=25)),
                ('author', models.CharField(max_length=25)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoverdeapp.district')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoverdeapp.region')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoverdeapp.status')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoverdeapp.type')),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoverdeapp.view')),
            ],
        ),
    ]
