# Generated by Django 3.1.7 on 2021-03-03 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoverdeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='region_id',
            new_name='region',
        ),
    ]
